// trellis-exl3 Marlin MoE kernels: host side + torch bindings (extension module `trellis_exl3_moe_kernels`).
//
// Routed experts of an EXL3 MoE layer, all experts of a projection stacked [E, ...] in the lane-major layout of
// `trellis_exl3_kernels.repack_trellis`, routed with vLLM's moe_align_block_size (sorted_token_ids / expert_ids /
// num_tokens_post_padded: the inputs vLLM's Marlin MoE takes). One layer =
//   1. moe_had_in      xh[s][slot] = Had128(fp16(x[slot / top_k]) * suh[expert(slot)][s])      (s = gate, up)
//   2. moe_gemm        gate+up of every moe block in ONE launch (shard map: column slices < I read slab 0, the
//                      others slab 1), output transform Had128 -> * svh[expert] inside the launch
//   3. moe_glu_had_in  xd[slot] = Had128(fp16(silu(g) * u) * suh_down[expert(slot)])
//   4. moe_gemm        down, output transform inside the launch
//   5. moe_combine     y[t] = sum_j w[t, j] * yd[t * top_k + j]   (fp32, ordered; fp16 or bf16 out)
//
// - GEMM: exl3_marlin_moe_template.h = vLLM's Marlin MoE kernel template (Apache-2.0) with the int4 dequant replaced
//   by EXL3's trellis decode (ExLlamaV3, MIT). Host launch logic follows vLLM v0.29.0
//   csrc/libtorch_stable/moe/marlin_moe_wna16/ops.cu (Apache-2.0, Neural Magic / vLLM project).
// - Hadamards: ExLlamaV3's had_hf_r_128_inner arithmetic (exl3_had.cuh); SiLU: ExLlamaV3's fp32 act_silu
//   (exl3_moe_coop_kernel.cuh, MIT).
//
// Decoded expert weights are bit-identical to exllamav3_ext.reconstruct; only the accumulation order differs.
// Every launch has a static shape for a fixed (tokens, top_k, moe_block_size): CUDA-graph safe. The number of valid
// moe blocks is read on the device (num_tokens_post_padded), as in Marlin MoE.

#define MARLIN_NAMESPACE_NAME trellis_exl3_marlin_moe

#include <torch/extension.h>
#include <c10/cuda/CUDAGuard.h>
#include <ATen/cuda/CUDAContext.h>
#include <cuda.h>
#include <cuda_fp16.h>
#include <cuda_bf16.h>
#include <cuda_runtime.h>
#include <climits>
#include <map>
#include <vector>

#include "exl3_marlin_moe_kernels.h"
#include "exl3_had.cuh"
#include "exl3_decode.cuh"   // TRELLIS_CB_MCG_LUT, decode_3inst (the table generator uses the codebook arithmetic itself)

namespace MARLIN_NAMESPACE_NAME {

// Variants compiled into this build: TRELLIS_MOE_VARIANTS(X) = X(mb, cb) ... (header generated by setup.py)
#include "trellis_moe_families.h"

#define TRELLIS_MOE_SEL(threads_, tn_, tk_, mb_, cb_, bits_)                                         \
  if (threads == threads_ && tn == tn_ && tk == tk_ && mb == mb_ && cb == cb_ && bits == bits_)     \
    return TRELLIS_MOE_KERNEL(threads_, tn_, tk_, mb_, cb_, bits_);
#define TRELLIS_MOE_SEL_VARIANT(mb, cb, bits) TRELLIS_MOE_THREAD_CFGS(TRELLIS_MOE_SEL, mb, cb, bits)

static MoeFuncPtr select_kernel(int threads, int tn, int tk, int mb, int cb, int bits) {
  TRELLIS_MOE_VARIANTS(TRELLIS_MOE_SEL_VARIANT)
  return nullptr;
}

struct ThreadCfg {
  int thread_k, thread_n, num_threads;
};

// Same tables and priority as Marlin MoE.
static const ThreadCfg small_cfgs[] = {{128, 128, 256}, {64, 128, 128}, {128, 64, 128}};
static const ThreadCfg large_cfgs[] = {{64, 256, 256}, {64, 128, 128}, {128, 64, 128}};

// Marlin MoE's get_kernel_cache_size for 4-bit weights, fp16 activations, no groups / zero points / act-order.
static int kernel_cache_size(const ThreadCfg& c, int thread_m_blocks) {
  int tb_k = c.thread_k, tb_n = c.thread_n, tb_m = thread_m_blocks * 16;
  int sh_block_meta_size = tb_m * 16;
  int sh_a_size = kMoeStages * (tb_m * tb_k) * 2;
  int sh_b_size = kMoeStages * (tb_k * tb_n / 8) * 4;
  int sh_red_size = tb_m * (tb_n + 8) * 2;
  int sh_bias_size = tb_n * 2;
  int tmp_size = (sh_b_size > sh_red_size ? sh_red_size : sh_b_size) + sh_bias_size;
  tmp_size = std::max(std::max(sh_b_size, sh_red_size), tmp_size);
  int sh_s_size = tb_n * 2 * kMoeStages;
  return tmp_size + sh_a_size + sh_s_size + sh_block_meta_size;
}

static bool valid_cfg(const ThreadCfg& c, int thread_m_blocks, int n, int k, int max_shared_mem, int shard_end,
                      bool need_had, int extra_smem = 0) {
  if (k % c.thread_k != 0 || n % c.thread_n != 0) return false;
  if (shard_end > 0 && shard_end % c.thread_n != 0) return false;  // a column slice must not straddle gate / up
  if (need_had && c.thread_n % 128 != 0) return false;             // in-launch output transform: whole 128-blocks
  return kernel_cache_size(c, thread_m_blocks) + extra_smem <= max_shared_mem;
}

static constexpr int kMaxBlocksPerSm = 4;
static int g_blocks_per_sm = -1;  // knob (moe_set_blocks_per_sm): -1 = automatic
// Automatic = Marlin MoE's determine_exec_config ("the config that allows the most co-resident blocks per SM wins"),
// EXCEPT for moe blocks of more than 16 rows, where co-resident blocks are capped at g_large_block_bps (default 1):
// larger blocks (more than 16 rows) run faster with 1 block per SM and the 64 x 256 thread config; at 8-row
// blocks Marlin's choice is already the best. Override with the moe_set_* knobs below.
static int g_large_block_bps = 1;  // knob (moe_set_large_block_bps): 0 = no cap
static int g_grid_limit = 0;       // knob (moe_set_grid_limit): > 0 caps the grid (blocks) below sms * bps: longer stripes, less per-slice overhead

struct DevState {
  int sms = 0;
  int max_shared_mem = 0;
  // Two scratch sets (locks + fp32 reduce buffer) so that two grouped GEMMs (the K=3 and K=4 classes of a mixed pack)
  // can run concurrently on two streams: `scratch` picks the set.
  at::Tensor locks[2];  // int32 [sms * 4], zero
  at::Tensor c_tmp[2];  // float: fp32 reduce scratch, Marlin MoE's upper bound (sms * 4 blocks x 64 rows x 256 cols, x2)
  at::Tensor lut_mcg;  // half [65536]: decode_3inst<1>(w) for every window (cb 13, shared-memory table decode)
};

// lut[w] = the MCG codebook value of window w, by the codebook arithmetic itself (bit-exact by construction)
__global__ void trellis_build_mcg_lut(half* __restrict__ out) {
  const uint32_t w = blockIdx.x * blockDim.x + threadIdx.x;
  if (w < 65536u) out[w] = decode_3inst<1>(w);
}
static constexpr int kLutBytes = 65536 * 2;

static DevState& dev_state(int device) {
  static std::map<int, DevState> states;
  auto it = states.find(device);
  if (it != states.end()) return it->second;
  DevState st;
  cudaDeviceGetAttribute(&st.sms, cudaDevAttrMultiProcessorCount, device);
  cudaDeviceGetAttribute(&st.max_shared_mem, cudaDevAttrMaxSharedMemoryPerBlockOptin, device);
  TORCH_CHECK(st.sms > 0 && st.max_shared_mem > 0, "trellis_exl3 moe: device query failed");
  auto dev = at::Device(at::kCUDA, device);
  for (int i = 0; i < 2; i++) {
    st.locks[i] = at::zeros({st.sms * kMaxBlocksPerSm}, at::TensorOptions().dtype(at::kInt).device(dev));
    st.c_tmp[i] = at::empty({(int64_t)st.sms * kMaxBlocksPerSm * 64 * 256 * 2}, at::TensorOptions().dtype(at::kFloat).device(dev));
  }
  st.lut_mcg = at::empty({65536}, at::TensorOptions().dtype(at::kHalf).device(dev));
  trellis_build_mcg_lut<<<64, 1024, 0, at::cuda::getCurrentCUDAStream().stream()>>>((half*)st.lut_mcg.data_ptr());
  states[device] = st;
  return states[device];
}

// One grouped launch. a: fp16 [shards * rows, k] (slab s = rows s*rows ..); b: [E, k/16, n/64, 32, 4]; c: fp16
// [rows, n]; sorted ids index ROWS (slots), i.e. Marlin MoE with top_k = 1. svh: fp16 [E, n] or nullptr.
static void gemm_launch(const half* a_ptr, const int* b_ptr, half* c_ptr, const half* svh, const int* sorted_ids,
                        const int* expert_ids, const int* num_post_padded, int moe_block_size, int rows, int n, int k,
                        int shard_end, int cb, int bits, int device, cudaStream_t stream, int force_thread_k,
                        int force_thread_n, int scratch) {
  DevState& st = dev_state(device);
  const int thread_m_blocks = (moe_block_size + 15) / 16;
  const bool m8 = moe_block_size == 8;
  const int sms = st.sms;
  int max_shared_mem = st.max_shared_mem;

  ThreadCfg cfg{-1, -1, -1};
  int bps = 1;
  const int extra_smem = cb == TRELLIS_CB_MCG_LUT ? kLutBytes : 0;   // the table lives in dynamic shared memory
  if (force_thread_k > 0 && force_thread_n > 0) {
    cfg = ThreadCfg{force_thread_k, force_thread_n, force_thread_k * force_thread_n / 64};
    TORCH_CHECK(valid_cfg(cfg, thread_m_blocks, n, k, max_shared_mem - 512, shard_end, svh != nullptr, extra_smem),
                "trellis_exl3 moe: bad forced thread config");
    if (g_blocks_per_sm > 0) bps = g_blocks_per_sm;
  } else {
    // Marlin MoE's determine_exec_config: the valid config that allows the most co-resident blocks per SM wins.
    const ThreadCfg* cfgs = thread_m_blocks > 1 ? large_cfgs : small_cfgs;
    constexpr int device_max_reg_size = 255 * 1024;
    int count = 0;
    for (int i = 0; i < 3; i++) {
      if (!valid_cfg(cfgs[i], thread_m_blocks, n, k, max_shared_mem - 512, shard_end, svh != nullptr, extra_smem)) continue;
      MoeFuncPtr kern = select_kernel(cfgs[i].num_threads, cfgs[i].thread_n, cfgs[i].thread_k, m8 ? 0 : thread_m_blocks, cb, bits);
      if (kern == nullptr) continue;
      int cache_size = kernel_cache_size(cfgs[i], thread_m_blocks) + extra_smem;
      cudaFuncAttributes attr;
      cudaFuncGetAttributes(&attr, kern);
      int reg_size = std::max((int)attr.numRegs, 1) * cfgs[i].num_threads * 4;
      int allow = std::min(device_max_reg_size / reg_size, max_shared_mem / (cache_size + 1536));
      allow = std::max(std::min(allow, thread_m_blocks == 1 ? 4 : 2), 1);
      if (n / cfgs[i].thread_n * rows * 4 < sms * allow) allow = std::max(n / cfgs[i].thread_n * rows * 4 / sms, 1);
      if (g_blocks_per_sm > 0) allow = std::min(allow, g_blocks_per_sm);
      else if (thread_m_blocks > 1 && g_large_block_bps > 0) allow = std::min(allow, g_large_block_bps);
      if (allow > count) {
        count = allow;
        cfg = cfgs[i];
        bps = allow;
      }
    }
  }
  TORCH_CHECK(cfg.thread_k != -1, "trellis_exl3 moe: no thread config for block=", moe_block_size, " k=", k, " n=", n);
  MoeFuncPtr kernel = select_kernel(cfg.num_threads, cfg.thread_n, cfg.thread_k, m8 ? 0 : thread_m_blocks, cb, bits);
  TORCH_CHECK(kernel != nullptr, "trellis_exl3 moe: kernel not compiled: threads=", cfg.num_threads, " thread_n=",
              cfg.thread_n, " thread_k=", cfg.thread_k, " moe_block=", moe_block_size, " cb=", cb, " K=", bits);
  TORCH_CHECK(bps >= 1 && bps <= kMaxBlocksPerSm);
  if (bps > 1) max_shared_mem = max_shared_mem / bps - 1024;
  TORCH_CHECK(kernel_cache_size(cfg, thread_m_blocks) + extra_smem <= max_shared_mem, "trellis_exl3 moe: shared memory too small");
  // EXL3: launch with what the kernel needs (Marlin passes the whole opt-in maximum, which pins one block per SM even
  // when registers would allow two): another launch's blocks (the other K class on a second stream, or a second
  // block of this one under TRELLIS_MOE_MINBLOCKS_M8=2) can then co-reside.
  const int dyn_smem = std::min(max_shared_mem, ((kernel_cache_size(cfg, thread_m_blocks) + extra_smem + 4096 + 1023) / 1024) * 1024);
  const int4* lut_ptr = cb == TRELLIS_CB_MCG_LUT ? (const int4*)st.lut_mcg.data_ptr() : nullptr;

  const int a_shard_stride = shard_end > 0 ? rows * (k / 8) : 0;  // int4 units (16 bytes) per input slab
  const int out_flags = svh ? 1 : 0;
  cudaFuncSetAttribute(kernel, cudaFuncAttributeMaxDynamicSharedMemorySize, max_shared_mem);
  // clang-format off
  const int grid = g_grid_limit > 0 ? std::min(sms * bps, g_grid_limit) : sms * bps;
  kernel<<<grid, cfg.num_threads, dyn_smem, stream>>>(
      (const int4*)a_ptr, (const int4*)b_ptr, (int4*)c_ptr, (int4*)st.c_tmp[scratch].data_ptr(), (const int4*)svh,
      nullptr, lut_ptr, nullptr, nullptr, nullptr,
      sorted_ids, expert_ids, num_post_padded, nullptr, /*top_k=*/1, /*mul_topk_weights=*/false,
      /*num_groups=*/-1, rows, n, k, (int*)st.locks[scratch].data_ptr(), /*has_bias=*/false, /*use_atomic_add=*/false,
      /*use_fp32_reduce=*/true, a_shard_stride, shard_end > 0 ? shard_end : INT_MAX, INT_MAX, INT_MAX, out_flags);
  // clang-format on
}

}  // namespace MARLIN_NAMESPACE_NAME

// ---------------------------------------------------------------------------------------------------------------
// Per-slot launches. Block (x, y) handles 128-block y of row x; 32 threads = the 32 lanes of the warp.

static constexpr float kHadScale = 0.088388347648f;  // 1/sqrt(128)

// xh[s * slots + slot] = Had128(fp16(x[slot / top_k]) * suh[ids[slot]][s]); grid (shards * slots, k / 128).
template <bool in_bf16, bool ids64>
__global__ __launch_bounds__(32)
void trellis_moe_had_in_kernel(const half* __restrict__ x, half* __restrict__ xh, const half* __restrict__ suh,
                              const void* __restrict__ ids, const int slots, const int top_k, const int shards,
                              const int num_experts) {
  const size_t width = (size_t)gridDim.y * 128;
  const int slot = blockIdx.x % slots, shard = blockIdx.x / slots;
  int64_t e = ids64 ? ((const int64_t*)ids)[slot] : (int64_t)((const int32_t*)ids)[slot];
  // An id outside [0, E) (padding / dummy tokens, expert-parallel sentinels) is dropped by moe_align_block_size, so the
  // GEMM never reads this slot and moe_combine skips it; clamp so the scale lookup stays inside suh.
  if (e < 0 || e >= num_experts) e = 0;
  const half* in = x + width * (slot / top_k) + blockIdx.y * 128;
  half* out = xh + width * blockIdx.x + blockIdx.y * 128;
  trellis_had_r_128_inner<in_bf16, false, true, false>(in, out, suh + width * (e * shards + shard), blockIdx.y * 32,
                                                      kHadScale);
}

// ExLlamaV3's fp32 SiLU (exl3_moe_coop_kernel.cuh act_silu)
__device__ __forceinline__ float trellis_act_silu(float x) {
  float e = __expf(-x);
  return x * __fdividef(1.0f, 1.0f + e);
}

// xd[slot] = Had128(fp16_rn(silu(g) * u) * suh_down[ids[slot]]); gu = [slots, 2 * inter] (gate | up), fp16.
// silu and the product are fp32, rounded to fp16 once (round to nearest even); from there it is exactly the input
// transform of a dense EXL3 linear, so moe_glu_had_in(gu) == had_in(fp16_rn(silu32(g) * u32)) bit for bit.
// grid (slots, inter / 128).
template <bool ids64>
__global__ __launch_bounds__(32)
void trellis_moe_glu_had_in_kernel(const half* __restrict__ gu, half* __restrict__ xd, half* __restrict__ act_tmp,
                                  const half* __restrict__ suh, const void* __restrict__ ids, const int num_experts) {
  const size_t inter = (size_t)gridDim.y * 128;
  const int slot = blockIdx.x;
  const int t = threadIdx.x & 31;
  int64_t e = ids64 ? ((const int64_t*)ids)[slot] : (int64_t)((const int32_t*)ids)[slot];
  if (e < 0 || e >= num_experts) e = 0;  // dropped slot (see moe_had_in): its gu row was never written, result unused
  const half4 g = ((const half4*)(gu + 2 * inter * slot + blockIdx.y * 128))[t];
  const half4 u = ((const half4*)(gu + 2 * inter * slot + inter + blockIdx.y * 128))[t];
  float2 g0 = __half22float2(g.x), g1 = __half22float2(g.y), u0 = __half22float2(u.x), u1 = __half22float2(u.y);
  half4 a;
  a.x = __floats2half2_rn(trellis_act_silu(g0.x) * u0.x, trellis_act_silu(g0.y) * u0.y);
  a.y = __floats2half2_rn(trellis_act_silu(g1.x) * u1.x, trellis_act_silu(g1.y) * u1.y);
  // stage the activation in the caller's scratch (its own lane slot: no conflict), then the standard transform
  half* act = act_tmp + inter * slot + blockIdx.y * 128;
  ((half4*)act)[t] = a;
  __syncthreads();
  trellis_had_r_128_inner<false, false, true, false>(act, xd + inter * slot + blockIdx.y * 128, suh + inter * e,
                                                    blockIdx.y * 32, kHadScale);
}

// y[t] = sum_j w[t, j] * yd[t * top_k + j], fp32 accumulation in slot order, one rounding to fp16 / bf16.
// grid (tokens, hidden / 128).
template <bool out_bf16, bool ids64>
__global__ __launch_bounds__(32)
void trellis_moe_combine_kernel(const half* __restrict__ yd, const float* __restrict__ w, half* __restrict__ y,
                               const void* __restrict__ ids, const int top_k, const int num_experts) {
  const size_t hidden = (size_t)gridDim.y * 128;
  const int tok = blockIdx.x;
  const int t = threadIdx.x & 31;
  float s0 = 0.0f, s1 = 0.0f, s2 = 0.0f, s3 = 0.0f;
  for (int j = 0; j < top_k; j++) {
    const size_t slot = (size_t)tok * top_k + j;
    const int64_t e = ids64 ? ((const int64_t*)ids)[slot] : (int64_t)((const int32_t*)ids)[slot];
    if (e < 0 || e >= num_experts) continue;  // dropped slot: yd row never written
    const half4 v = ((const half4*)(yd + hidden * slot + blockIdx.y * 128))[t];
    const float wj = w[(size_t)tok * top_k + j];
    float2 lo = __half22float2(v.x), hi = __half22float2(v.y);
    s0 += wj * lo.x; s1 += wj * lo.y; s2 += wj * hi.x; s3 += wj * hi.y;
  }
  half* out = y + hidden * tok + blockIdx.y * 128;
  if constexpr (out_bf16) {
    float2 f0, f1;
    f0.x = s0; f0.y = s1; f1.x = s2; f1.y = s3;
    __nv_bfloat162* wr = ((__nv_bfloat162*)out) + 2 * t;
    wr[0] = __float22bfloat162_rn(f0);
    wr[1] = __float22bfloat162_rn(f1);
  } else {
    half4 o;
    o.x = __floats2half2_rn(s0, s1);
    o.y = __floats2half2_rn(s2, s3);
    ((half4*)out)[t] = o;
  }
}

// ---------------------------------------------------------------------------------------------------------------
// Grid-strided variants (prefill): instead of one 32-thread block per (row, 128-block) item - 4.2 M blocks per layer at
// 8k tokens - a FIXED grid of 256-thread blocks (8 warps each) strides over the items, as the dense template's
// cooperative prologue does. Warp g = blockIdx.x * 8 + threadIdx.x / 32 handles items g, g + G, g + 2G, ... (G = warps
// in the grid); all 32 lanes of a warp run the same trip count, so the warp shuffles inside the Hadamard stay in
// lockstep. Same statements per item as the kernels above => bit-identical results (checked by the parity tools).
// g_gs_blocks (knob moe_set_gridstride_blocks): -1 = automatic, 0 = always per-item launches (above), n > 0 = always n
// grid blocks. Automatic (grid-striding with enough blocks is faster at high token counts, worse with too few
// blocks): grid-strided with up to 8,448 blocks once there are at least
// 16,384 items (64 tokens here), per-item launches below that (decode sizes: no measurable difference).
static int g_gs_blocks = -1;
static constexpr int64_t kGsAutoMinItems = 16384;  // 64 tokens x top-8 x 2 slabs x 16 blocks
static constexpr int kGsAutoBlocks = 8448;

static int gs_blocks_for(int64_t items) {
  if (g_gs_blocks >= 0) return g_gs_blocks;
  return items >= kGsAutoMinItems ? kGsAutoBlocks : 0;
}

template <bool in_bf16, bool ids64>
__global__ __launch_bounds__(256)
void trellis_moe_had_in_gs_kernel(const half* __restrict__ x, half* __restrict__ xh, const half* __restrict__ suh,
                                 const void* __restrict__ ids, const int slots, const int top_k, const int shards,
                                 const int num_experts, const int kb) {
  const size_t width = (size_t)kb * 128;
  const int64_t total = (int64_t)shards * slots * kb, stride = (int64_t)gridDim.x * 8;
  for (int64_t w = (int64_t)blockIdx.x * 8 + threadIdx.x / 32; w < total; w += stride) {
    const int blk = (int)(w % kb);
    const int64_t rs = w / kb;
    const int slot = (int)(rs % slots), shard = (int)(rs / slots);
    int64_t e = ids64 ? ((const int64_t*)ids)[slot] : (int64_t)((const int32_t*)ids)[slot];
    if (e < 0 || e >= num_experts) e = 0;
    trellis_had_r_128_inner<in_bf16, false, true, false>(x + width * (slot / top_k) + blk * 128, xh + width * rs + blk * 128,
                                                        suh + width * (e * shards + shard), blk * 32, kHadScale);
  }
}

template <bool ids64>
__global__ __launch_bounds__(256)
void trellis_moe_glu_had_in_gs_kernel(const half* __restrict__ gu, half* __restrict__ xd, half* __restrict__ act_tmp,
                                     const half* __restrict__ suh, const void* __restrict__ ids, const int num_experts,
                                     const int slots, const int kb) {
  const size_t inter = (size_t)kb * 128;
  const int64_t total = (int64_t)slots * kb, stride = (int64_t)gridDim.x * 8;
  const int t = threadIdx.x & 31;
  for (int64_t w = (int64_t)blockIdx.x * 8 + threadIdx.x / 32; w < total; w += stride) {
    const int blk = (int)(w % kb);
    const int64_t slot = w / kb;
    int64_t e = ids64 ? ((const int64_t*)ids)[slot] : (int64_t)((const int32_t*)ids)[slot];
    if (e < 0 || e >= num_experts) e = 0;
    const half4 g = ((const half4*)(gu + 2 * inter * slot + blk * 128))[t];
    const half4 u = ((const half4*)(gu + 2 * inter * slot + inter + blk * 128))[t];
    float2 g0 = __half22float2(g.x), g1 = __half22float2(g.y), u0 = __half22float2(u.x), u1 = __half22float2(u.y);
    half4 a;
    a.x = __floats2half2_rn(trellis_act_silu(g0.x) * u0.x, trellis_act_silu(g0.y) * u0.y);
    a.y = __floats2half2_rn(trellis_act_silu(g1.x) * u1.x, trellis_act_silu(g1.y) * u1.y);
    half* act = act_tmp + inter * slot + blk * 128;
    ((half4*)act)[t] = a;
    // No __syncthreads() here: it would synchronise the whole 256-thread block, and the 8 warps of a block have
    // different trip counts at the tail (hang). Each lane reads back only the vector it has just written itself.
    trellis_had_r_128_inner<false, false, true, false>(act, xd + inter * slot + blk * 128, suh + inter * e, blk * 32, kHadScale);
  }
}

// ---------------------------------------------------------------------------------------------------------------
// Torch entry points

static bool is_16bit_float(const at::Tensor& t) { return t.dtype() == at::kHalf || t.dtype() == at::kBFloat16; }
static bool is_index(const at::Tensor& t) { return t.dtype() == at::kInt || t.dtype() == at::kLong; }

// -> EXL3 K of the stack: [E, k/16, n/64, 32, 4] = K=4 (lane-major repack), [E, k/16, n/64, 4, 24] = K=3 (tiles as stored)
static int check_stack(const at::Tensor& b, int64_t k, int64_t n) {
  TORCH_CHECK(b.is_cuda() && b.is_contiguous() && b.dtype() == at::kInt, "stacked trellis must be contiguous int32 CUDA");
  TORCH_CHECK(b.dim() == 5 && ((b.size(3) == 32 && b.size(4) == 4) || (b.size(3) == 4 && b.size(4) == 24)),
              "stacked trellis must be [E, k/16, n/64, 32, 4] (K=4) or [E, k/16, n/64, 4, 24] (K=3)");
  TORCH_CHECK(b.size(1) * 16 == k && b.size(2) * 64 == n, "stacked trellis shape does not match k, n");
  return b.size(4) == 24 ? 3 : 4;
}

// Grouped rotated-basis GEMM (+ optional in-launch output transform). a fp16 [shards * rows, k]; c fp16 [rows, n];
// sorted_ids int32 [padded] index rows, padding entries >= rows; expert_ids int32 [padded / block];
// num_post_padded int32 [1]; svh fp16 [E, n] or undefined; shard_end = column where shard 1 starts (0 = one shard).
void moe_gemm(const at::Tensor& a, const at::Tensor& b, at::Tensor& c, const c10::optional<at::Tensor>& svh,
              const at::Tensor& sorted_ids, const at::Tensor& expert_ids, const at::Tensor& num_post_padded,
              int64_t moe_block_size, int64_t shard_end, int64_t cb, int64_t thread_k, int64_t thread_n, int64_t scratch) {
  const at::cuda::OptionalCUDAGuard device_guard(a.device());
  TORCH_CHECK(a.dim() == 2 && c.dim() == 2 && a.dtype() == at::kHalf && c.dtype() == at::kHalf);
  TORCH_CHECK(a.is_contiguous() && c.is_contiguous());
  const int64_t rows = c.size(0), k = a.size(1), n = c.size(1), shards = shard_end > 0 ? 2 : 1;
  TORCH_CHECK(a.size(0) == shards * rows, "a must be [shards * rows, k]");
  const int bits = check_stack(b, k, n);
  TORCH_CHECK(moe_block_size == 8 || (moe_block_size % 16 == 0 && moe_block_size >= 16 && moe_block_size <= 64),
              "unsupported moe_block_size ", moe_block_size);
  TORCH_CHECK(sorted_ids.dtype() == at::kInt && expert_ids.dtype() == at::kInt && num_post_padded.dtype() == at::kInt);
  // moe_align_block_size sizes sorted_ids as T * top_k + E * (block - 1), which need not be a multiple of the block
  // size (e.g. 255 tokens, block 16); the kernel only visits num_post_padded / block full blocks, the tail is slack.
  TORCH_CHECK(sorted_ids.is_contiguous() && expert_ids.is_contiguous() && num_post_padded.numel() == 1);
  TORCH_CHECK(expert_ids.numel() >= sorted_ids.numel() / moe_block_size, "expert_ids too short");
  TORCH_CHECK(shard_end >= 0 && shard_end < n && shard_end % 128 == 0);
  TORCH_CHECK((int64_t)shards * rows * (k / 8) < INT_MAX, "input slabs exceed the kernel's 32-bit offsets");
  const half* svh_ptr = nullptr;
  if (svh.has_value()) {
    TORCH_CHECK(svh->dtype() == at::kHalf && svh->is_contiguous() && svh->dim() == 2 && svh->size(0) == b.size(0) &&
                svh->size(1) == n, "svh must be fp16 [E, n]");
    svh_ptr = (const half*)svh->data_ptr();
  }
  TORCH_CHECK(scratch == 0 || scratch == 1, "scratch must be 0 or 1");
  if (rows == 0) return;
  cudaStream_t stream = at::cuda::getCurrentCUDAStream().stream();
  trellis_exl3_marlin_moe::gemm_launch((const half*)a.data_ptr(), (const int*)b.data_ptr(), (half*)c.data_ptr(), svh_ptr,
                                      (const int*)sorted_ids.data_ptr(), (const int*)expert_ids.data_ptr(),
                                      (const int*)num_post_padded.data_ptr(), (int)moe_block_size, (int)rows, (int)n,
                                      (int)k, (int)shard_end, (int)cb, bits, a.get_device(), stream, (int)thread_k,
                                      (int)thread_n, (int)scratch);
}

// xh [shards * slots, k] fp16 <- x [tokens, k] fp16 | bf16, suh [E, shards, k] fp16, ids [tokens, top_k] int32 | int64
void moe_had_in(const at::Tensor& x, const at::Tensor& suh, const at::Tensor& ids, at::Tensor& xh) {
  const at::cuda::OptionalCUDAGuard device_guard(x.device());
  TORCH_CHECK(x.dim() == 2 && is_16bit_float(x) && x.is_contiguous() && x.size(1) % 128 == 0);
  TORCH_CHECK(ids.dim() == 2 && is_index(ids) && ids.is_contiguous() && ids.size(0) == x.size(0));
  TORCH_CHECK(suh.dim() == 3 && suh.dtype() == at::kHalf && suh.is_contiguous() && suh.size(2) == x.size(1));
  const int64_t tokens = x.size(0), k = x.size(1), top_k = ids.size(1), shards = suh.size(1), slots = tokens * top_k;
  TORCH_CHECK(xh.dtype() == at::kHalf && xh.is_contiguous() && xh.numel() >= shards * slots * k);
  if (slots == 0) return;
  cudaStream_t stream = at::cuda::getCurrentCUDAStream().stream();
  dim3 grid((unsigned)(shards * slots), (unsigned)(k / 128));
  const bool bf = x.dtype() == at::kBFloat16, i64 = ids.dtype() == at::kLong;
  const half* xp = (const half*)x.data_ptr(); half* op = (half*)xh.data_ptr();
  const half* sp = (const half*)suh.data_ptr(); const void* ip = ids.data_ptr();
  if (const int gsb = gs_blocks_for(shards * slots * (k / 128)); gsb > 0) {
    const int kb = (int)(k / 128), ne = (int)suh.size(0);
    const int64_t warps = shards * slots * kb;
    const int gb = (int)std::min<int64_t>(gsb, (warps + 7) / 8);
    // clang-format off
    if (bf && i64)  trellis_moe_had_in_gs_kernel<true, true><<<gb, 256, 0, stream>>>(xp, op, sp, ip, (int)slots, (int)top_k, (int)shards, ne, kb);
    else if (bf)    trellis_moe_had_in_gs_kernel<true, false><<<gb, 256, 0, stream>>>(xp, op, sp, ip, (int)slots, (int)top_k, (int)shards, ne, kb);
    else if (i64)   trellis_moe_had_in_gs_kernel<false, true><<<gb, 256, 0, stream>>>(xp, op, sp, ip, (int)slots, (int)top_k, (int)shards, ne, kb);
    else            trellis_moe_had_in_gs_kernel<false, false><<<gb, 256, 0, stream>>>(xp, op, sp, ip, (int)slots, (int)top_k, (int)shards, ne, kb);
    // clang-format on
    return;
  }
  // clang-format off
  if (bf && i64)       trellis_moe_had_in_kernel<true, true><<<grid, 32, 0, stream>>>(xp, op, sp, ip, (int)slots, (int)top_k, (int)shards, (int)suh.size(0));
  else if (bf)         trellis_moe_had_in_kernel<true, false><<<grid, 32, 0, stream>>>(xp, op, sp, ip, (int)slots, (int)top_k, (int)shards, (int)suh.size(0));
  else if (i64)        trellis_moe_had_in_kernel<false, true><<<grid, 32, 0, stream>>>(xp, op, sp, ip, (int)slots, (int)top_k, (int)shards, (int)suh.size(0));
  else                 trellis_moe_had_in_kernel<false, false><<<grid, 32, 0, stream>>>(xp, op, sp, ip, (int)slots, (int)top_k, (int)shards, (int)suh.size(0));
  // clang-format on
}

// xd [slots, inter] fp16 <- gu [slots, 2 * inter] fp16 (gate | up), suh_down [E, inter], ids [tokens, top_k];
// act_tmp: fp16 scratch [slots, inter] (receives fp16_rn(silu(g) * u), the activation tensor itself)
void moe_glu_had_in(const at::Tensor& gu, const at::Tensor& suh, const at::Tensor& ids, at::Tensor& act_tmp,
                    at::Tensor& xd) {
  const at::cuda::OptionalCUDAGuard device_guard(gu.device());
  TORCH_CHECK(gu.dim() == 2 && gu.dtype() == at::kHalf && gu.is_contiguous() && gu.size(1) % 256 == 0);
  const int64_t slots = gu.size(0), inter = gu.size(1) / 2;
  TORCH_CHECK(is_index(ids) && ids.is_contiguous() && ids.numel() == slots);
  TORCH_CHECK(suh.dim() == 2 && suh.dtype() == at::kHalf && suh.is_contiguous() && suh.size(1) == inter);
  TORCH_CHECK(xd.dtype() == at::kHalf && xd.is_contiguous() && xd.numel() >= slots * inter);
  TORCH_CHECK(act_tmp.dtype() == at::kHalf && act_tmp.is_contiguous() && act_tmp.numel() >= slots * inter);
  TORCH_CHECK(act_tmp.data_ptr() != xd.data_ptr() && act_tmp.data_ptr() != gu.data_ptr());
  if (slots == 0) return;
  cudaStream_t stream = at::cuda::getCurrentCUDAStream().stream();
  dim3 grid((unsigned)slots, (unsigned)(inter / 128));
  if (const int gsb = gs_blocks_for(slots * (inter / 128)); gsb > 0) {
    const int kb = (int)(inter / 128), ne = (int)suh.size(0);
    const int gb = (int)std::min<int64_t>(gsb, (slots * kb + 7) / 8);
    // clang-format off
    if (ids.dtype() == at::kLong)
      trellis_moe_glu_had_in_gs_kernel<true><<<gb, 256, 0, stream>>>((const half*)gu.data_ptr(), (half*)xd.data_ptr(), (half*)act_tmp.data_ptr(), (const half*)suh.data_ptr(), ids.data_ptr(), ne, (int)slots, kb);
    else
      trellis_moe_glu_had_in_gs_kernel<false><<<gb, 256, 0, stream>>>((const half*)gu.data_ptr(), (half*)xd.data_ptr(), (half*)act_tmp.data_ptr(), (const half*)suh.data_ptr(), ids.data_ptr(), ne, (int)slots, kb);
    // clang-format on
    return;
  }
  // clang-format off
  if (ids.dtype() == at::kLong)
    trellis_moe_glu_had_in_kernel<true><<<grid, 32, 0, stream>>>((const half*)gu.data_ptr(), (half*)xd.data_ptr(), (half*)act_tmp.data_ptr(), (const half*)suh.data_ptr(), ids.data_ptr(), (int)suh.size(0));
  else
    trellis_moe_glu_had_in_kernel<false><<<grid, 32, 0, stream>>>((const half*)gu.data_ptr(), (half*)xd.data_ptr(), (half*)act_tmp.data_ptr(), (const half*)suh.data_ptr(), ids.data_ptr(), (int)suh.size(0));
  // clang-format on
}

// y [tokens, hidden] fp16 | bf16 <- yd [tokens * top_k, hidden] fp16, w [tokens, top_k] float32; slots whose id is
// outside [0, num_experts) are skipped (moe_align_block_size dropped them, their yd row was never written)
void moe_combine(const at::Tensor& yd, const at::Tensor& w, const at::Tensor& ids, int64_t num_experts, at::Tensor& y) {
  const at::cuda::OptionalCUDAGuard device_guard(yd.device());
  TORCH_CHECK(yd.dim() == 2 && yd.dtype() == at::kHalf && yd.is_contiguous() && yd.size(1) % 128 == 0);
  TORCH_CHECK(w.dim() == 2 && w.dtype() == at::kFloat && w.is_contiguous());
  TORCH_CHECK(y.dim() == 2 && is_16bit_float(y) && y.is_contiguous() && y.size(1) == yd.size(1));
  const int64_t tokens = y.size(0), top_k = w.size(1);
  TORCH_CHECK(w.size(0) == tokens && yd.size(0) == tokens * top_k);
  TORCH_CHECK(is_index(ids) && ids.is_contiguous() && ids.numel() == tokens * top_k && num_experts > 0);
  if (tokens == 0) return;
  cudaStream_t stream = at::cuda::getCurrentCUDAStream().stream();
  dim3 grid((unsigned)tokens, (unsigned)(y.size(1) / 128));
  // clang-format off
  const half* ydp = (const half*)yd.data_ptr(); const float* wp = (const float*)w.data_ptr(); half* yp = (half*)y.data_ptr();
  const bool bf = y.dtype() == at::kBFloat16, i64 = ids.dtype() == at::kLong;
  if (bf && i64)  trellis_moe_combine_kernel<true, true><<<grid, 32, 0, stream>>>(ydp, wp, yp, ids.data_ptr(), (int)top_k, (int)num_experts);
  else if (bf)    trellis_moe_combine_kernel<true, false><<<grid, 32, 0, stream>>>(ydp, wp, yp, ids.data_ptr(), (int)top_k, (int)num_experts);
  else if (i64)   trellis_moe_combine_kernel<false, true><<<grid, 32, 0, stream>>>(ydp, wp, yp, ids.data_ptr(), (int)top_k, (int)num_experts);
  else            trellis_moe_combine_kernel<false, false><<<grid, 32, 0, stream>>>(ydp, wp, yp, ids.data_ptr(), (int)top_k, (int)num_experts);
  // clang-format on
}

void moe_init_device(int64_t device) { trellis_exl3_marlin_moe::dev_state((int)device); }

void moe_set_gridstride_blocks(int64_t n) {
  TORCH_CHECK(n >= -1 && n <= (1 << 22));
  g_gs_blocks = (int)n;
}

void moe_set_large_block_bps(int64_t n) {
  TORCH_CHECK(n >= 0 && n <= trellis_exl3_marlin_moe::kMaxBlocksPerSm);
  trellis_exl3_marlin_moe::g_large_block_bps = (int)n;
}

void moe_set_blocks_per_sm(int64_t n) {
  TORCH_CHECK(n == -1 || (n >= 1 && n <= trellis_exl3_marlin_moe::kMaxBlocksPerSm));
  trellis_exl3_marlin_moe::g_blocks_per_sm = (int)n;
}

void moe_set_grid_limit(int64_t n) {
  TORCH_CHECK(n >= 0);
  trellis_exl3_marlin_moe::g_grid_limit = (int)n;
}

// ---------------------------------------------------------------------------------------------------------------
// Decode-sized routing for mixed-K layers: ONE launch produces, for every K class, the (sorted_token_ids, expert_ids,
// num_tokens_post_padded) triple vLLM's moe_align_block_size would produce with that class's expert_map and
// ignore_invalid_experts=True (padding slots = numel, padding blocks = -1, local expert ids, per-expert counts padded
// to the class's block size, experts in ascending global order). vLLM's kernel is generic (grids, cub scans over 256
// experts, a separate fill launch) and much slower per class at decode sizes; this fused launch does both classes at once.
// One block of 1024 threads; slots <= TRELLIS_ALIGN_MAX_SLOTS, experts <= 1024, classes <= 2.
#include <cub/cub.cuh>
#define TRELLIS_ALIGN_MAX_SLOTS 4096
#define TRELLIS_ALIGN_MAX_E 1024

__global__ __launch_bounds__(1024)
void trellis_moe_align_decode_kernel(const int* __restrict__ topk_ids, int slots, int num_experts, int num_classes,
                                    const int* __restrict__ map0, const int* __restrict__ map1, int block0, int block1,
                                    int* __restrict__ sorted0, int* __restrict__ sorted1, int cap0, int cap1,
                                    int* __restrict__ eids0, int* __restrict__ eids1, int mblk0, int mblk1,
                                    int* __restrict__ post0, int* __restrict__ post1) {
  __shared__ int count[TRELLIS_ALIGN_MAX_E];
  __shared__ int start[TRELLIS_ALIGN_MAX_E];
  __shared__ int fill[TRELLIS_ALIGN_MAX_E];
  __shared__ int total_c[2];
  using Scan = cub::BlockScan<int, 1024>;
  __shared__ typename Scan::TempStorage tmp;
  const int t = threadIdx.x;
  for (int e = t; e < num_experts; e += blockDim.x) { count[e] = 0; fill[e] = 0; }
  __syncthreads();
  for (int s = t; s < slots; s += blockDim.x) {
    int e = topk_ids[s];
    if (e >= 0 && e < num_experts) atomicAdd(&count[e], 1);
  }
  __syncthreads();
  for (int c = 0; c < num_classes; c++) {
    const int* map = c == 0 ? map0 : map1;
    const int block = c == 0 ? block0 : block1;
    int padded = 0;
    if (t < num_experts && map[t] >= 0) padded = ((count[t] + block - 1) / block) * block;
    int excl, total;
    Scan(tmp).ExclusiveSum(padded, excl, total);
    if (t < num_experts) start[t] = excl;
    if (t == 0) total_c[c] = total;
    __syncthreads();
    int* sorted = c == 0 ? sorted0 : sorted1;
    int* eids = c == 0 ? eids0 : eids1;
    const int cap = c == 0 ? cap0 : cap1;
    const int mblk = c == 0 ? mblk0 : mblk1;
    // expert ids per block (local ids), padding blocks -1
    if (t < num_experts && map[t] >= 0)
      for (int i = start[t]; i < start[t] + padded; i += block) eids[i / block] = map[t];
    for (int i = (total + block - 1) / block + t; i < mblk; i += blockDim.x) eids[i] = -1;
    // padding slots = numel (vLLM's sentinel); then the class's slots into their expert's range
    for (int i = total + t; i < cap; i += blockDim.x) sorted[i] = slots;
    for (int i = t; i < total; i += blockDim.x) sorted[i] = slots;   // pad the tails inside expert ranges too
    __syncthreads();
    for (int s = t; s < slots; s += blockDim.x) {
      int e = topk_ids[s];
      if (e >= 0 && e < num_experts && map[e] >= 0) {
        int pos = start[e] + atomicAdd(&fill[e], 1);
        sorted[pos] = s;
      }
    }
    if (t == 0) *(c == 0 ? post0 : post1) = total;
    __syncthreads();
  }
}

// topk_ids int32 [tokens, top_k] (global ids); maps: int32 [E] per class; outputs preallocated per class
void moe_align_decode(const at::Tensor& topk_ids, const std::vector<at::Tensor>& maps, const std::vector<int64_t>& blocks,
                      int64_t num_experts, const std::vector<at::Tensor>& sorted, const std::vector<at::Tensor>& eids,
                      const std::vector<at::Tensor>& post) {
  const at::cuda::OptionalCUDAGuard device_guard(topk_ids.device());
  const int nc = (int)maps.size();
  TORCH_CHECK(nc >= 1 && nc <= 2 && (int)blocks.size() == nc && (int)sorted.size() == nc && (int)eids.size() == nc && (int)post.size() == nc);
  TORCH_CHECK(topk_ids.dtype() == at::kInt && topk_ids.is_contiguous());
  const int slots = (int)topk_ids.numel();
  TORCH_CHECK(slots <= TRELLIS_ALIGN_MAX_SLOTS && num_experts <= TRELLIS_ALIGN_MAX_E, "moe_align_decode: decode sizes only");
  for (int c = 0; c < nc; c++) {
    TORCH_CHECK(maps[c].dtype() == at::kInt && maps[c].numel() == num_experts && maps[c].is_contiguous());
    TORCH_CHECK(sorted[c].dtype() == at::kInt && eids[c].dtype() == at::kInt && post[c].dtype() == at::kInt);
    TORCH_CHECK(eids[c].numel() * blocks[c] >= sorted[c].numel(), "expert_ids too short");
  }
  cudaStream_t stream = at::cuda::getCurrentCUDAStream().stream();
  auto P = [&](const std::vector<at::Tensor>& v, int c) { return c < nc ? v[c].data_ptr<int>() : nullptr; };
  auto M = [&](int c) { return c < nc ? maps[c].data_ptr<int>() : nullptr; };
  trellis_moe_align_decode_kernel<<<1, 1024, 0, stream>>>(
      topk_ids.data_ptr<int>(), slots, (int)num_experts, nc, M(0), M(1), (int)blocks[0], nc > 1 ? (int)blocks[1] : 1,
      P(sorted, 0), P(sorted, 1), (int)sorted[0].numel(), nc > 1 ? (int)sorted[1].numel() : 0,
      P(eids, 0), P(eids, 1), (int)eids[0].numel(), nc > 1 ? (int)eids[1].numel() : 0, P(post, 0), P(post, 1));
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("moe_align_decode", &moe_align_decode, "decode-sized routing for mixed-K layers: vLLM moe_align_block_size outputs for every K class in ONE launch",
        py::arg("topk_ids"), py::arg("maps"), py::arg("blocks"), py::arg("num_experts"), py::arg("sorted"), py::arg("expert_ids"), py::arg("num_post"));
  m.def("moe_gemm", &moe_gemm, "grouped rotated-basis EXL3 GEMM over moe blocks (+ in-launch output transform)",
        py::arg("a"), py::arg("b"), py::arg("c"), py::arg("svh"), py::arg("sorted_ids"), py::arg("expert_ids"),
        py::arg("num_post_padded"), py::arg("moe_block_size"), py::arg("shard_end"), py::arg("cb"),
        py::arg("thread_k") = -1, py::arg("thread_n") = -1, py::arg("scratch") = 0);
  m.def("moe_had_in", &moe_had_in, "per-slot input transform with per-expert suh (gather + scale + Had128)");
  m.def("moe_glu_had_in", &moe_glu_had_in, "silu(gate) * up -> fp16 -> per-expert suh -> Had128 (down input)");
  m.def("moe_combine", &moe_combine, "router-weighted fp32 sum over a token's top-k slots");
  m.def("moe_init_device", &moe_init_device, "allocate per-device state (locks, fp32 reduce scratch)");
  m.def("moe_set_gridstride_blocks", &moe_set_gridstride_blocks,
        "knob: -1 = automatic (default), 0 = one 32-thread block per (row, 128-block) item in the per-slot transforms, n > 0 = n grid-strided 256-thread blocks");
  m.def("moe_set_large_block_bps", &moe_set_large_block_bps,
        "knob: cap of co-resident blocks per SM for moe blocks of more than 16 rows (default 1, 0 = Marlin MoE's choice)");
  m.def("moe_set_blocks_per_sm", &moe_set_blocks_per_sm, "knob: co-resident blocks per SM (-1 = Marlin MoE's choice)");
  m.def("moe_set_grid_limit", &moe_set_grid_limit, "knob: cap the GEMM grid at n blocks (0 = sms * blocks per SM)");
}
