"""Build the `trellis_exl3_kernels` torch extension (Marlin EXL3 kernels for sm_86).

Run inside the sglang-exl3:dev image through csrc/build.sh (sets TORCH_CUDA_ARCH_LIST=8.6):

    ./build.sh            # full: rows<=8/16/32/48/64 families, MUL1 + MCG
    ./build.sh small      # rows<=16 families, MUL1 only (fast iteration)

Result: build/lib/trellis_exl3_kernels*.so (put that dir on PYTHONPATH to import it).

Env: TRELLIS_MBS="0,1,2,3,4" row-block families (0 = rows<=8 transposed MMA, m = rows<=16m);
     TRELLIS_CODEBOOKS="1,2" (0 = 3INST, 1 = MCG, 2 = MUL1); TRELLIS_KBITS="3,4,5,6" (EXL3 bits per weight; 3, 5 = byte-exact tile staging, K3 / K5).
     One generated .cu per (family, codebook, K). TRELLIS_WRAP_LOAD=0 restores the lane shuffle for the K=4 wrap bits
     (default 1: a second shared-memory load, same decoded bits).
"""
import os
from setuptools import setup
from torch.utils import cpp_extension

here = os.path.dirname(os.path.abspath(__file__))
mbs = [m.strip() for m in os.environ.get("TRELLIS_MBS", "0,1,2,3,4").split(",") if m.strip()]
cbs = [c.strip() for c in os.environ.get("TRELLIS_CODEBOOKS", "1,2").split(",") if c.strip()]
kbs = [b.strip() for b in os.environ.get("TRELLIS_KBITS", "3,4,5,6").split(",") if b.strip()]   # K3: default includes 3; K5: and 5
gen = os.path.join(here, "build", "gen")
os.makedirs(gen, exist_ok=True)
sources = ["exl3_marlin.cu"]
variants = [(mb, cb, kb) for mb in mbs for cb in cbs for kb in kbs]
for mb, cb, kb in variants:
    path = os.path.join(gen, f"inst_mb{mb}_cb{cb}_k{kb}.cu")
    text = (f"#define TRELLIS_INST_MB {mb}\n#define TRELLIS_INST_CB {cb}\n#define TRELLIS_INST_KB {kb}\n"
            "#include \"exl3_marlin_inst.h\"\n")
    if not os.path.exists(path) or open(path).read() != text:
        open(path, "w").write(text)
    sources.append(os.path.relpath(path, here))
fam = os.path.join(gen, "trellis_families.h")
fam_text = ("// generated by setup.py\n#pragma once\n#define TRELLIS_VARIANTS(X) "
            + " ".join(f"X({mb}, {cb}, {kb})" for mb, cb, kb in variants) + "\n")
if not os.path.exists(fam) or open(fam).read() != fam_text:
    open(fam, "w").write(fam_text)
# kernels are instantiated in their own translation units: their host stubs must have external linkage
nvcc = ["-lineinfo", "-O3", "--use_fast_math", "-std=c++17", "-static-global-template-stub=false",
        "-DTRELLIS_WRAP_LOAD=" + os.environ.get("TRELLIS_WRAP_LOAD", "1"),
        "-DTRELLIS_PROBES=" + os.environ.get("TRELLIS_PROBES", "0"),
        "-DTRELLIS_SLOT_REDUCE=" + os.environ.get("TRELLIS_SLOT_REDUCE", "1"),
        "-DTRELLIS_MOE_MINBLOCKS_M8=" + os.environ.get("TRELLIS_MOE_MINBLOCKS_M8", "2"),
        "-DTRELLIS_MCG_SELFADD=" + os.environ.get("TRELLIS_MCG_SELFADD", "1"),
        "-DTRELLIS_K3_IMAD_SHIFTS=" + os.environ.get("TRELLIS_K3_IMAD_SHIFTS", "0")]
if os.environ.get("TRELLIS_FORCE_OUT_FLAGS"):   # experiment only: every GEMM launch applies the output transform
    nvcc.append("-DTRELLIS_FORCE_OUT_FLAGS=" + os.environ["TRELLIS_FORCE_OUT_FLAGS"])

ext_modules = [
    cpp_extension.CUDAExtension(
        "trellis_exl3_kernels",
        sources,
        include_dirs=[here, os.path.join(here, "third_party", "marlin"), gen],
        extra_compile_args={"cxx": ["-O3"], "nvcc": nvcc},
    )
]

# ---- MoE front (begin): second extension `trellis_exl3_moe_kernels` = exl3_marlin_moe.cu + one generated unit per
# (moe block family, codebook), K = 4 only. TRELLIS_MOE=0 skips it, TRELLIS_MOE=only builds nothing else;
# TRELLIS_MOE_MBS="0,1,2,3,4" (0 = 8 rows per moe block, m = 16m rows), TRELLIS_MOE_CODEBOOKS defaults to TRELLIS_CODEBOOKS.
moe_mode = os.environ.get("TRELLIS_MOE", "1")
if moe_mode != "0":
    moe_mbs = [m.strip() for m in os.environ.get("TRELLIS_MOE_MBS", "0,1,2,3,4").split(",") if m.strip()]
    moe_cbs = [c.strip() for c in os.environ.get("TRELLIS_MOE_CODEBOOKS", ",".join(c for c in cbs if c in ("0", "1", "2"))).split(",") if c.strip()]
    # TRELLIS_MOE_BITS="3,4": EXL3 K of the experts (3 = K = 3 experts, byte-exact tile staging; 4 = lane-major repack)
    moe_bits = [b.strip() for b in os.environ.get("TRELLIS_MOE_BITS", "3,4").split(",") if b.strip()]
    moe_sources = ["exl3_marlin_moe.cu", "exl3_moe_orig_builder.cu"]
    # cb 13 = MCG through a 128 KB shared-memory table: decode block families only (0 = 8 rows, 1 = 16 rows); larger
    # families have no shared memory left for the table. TRELLIS_MOE_LUT=0 leaves it out of the build.
    moe_variants = [(mb, cb, kb) for mb in moe_mbs for cb in moe_cbs for kb in moe_bits]
    if os.environ.get("TRELLIS_MOE_LUT", "0") == "1" and "1" in moe_cbs:   # off: dead end at decode sizes
        moe_variants += [(mb, "13", kb) for mb in moe_mbs if mb in ("0", "1") for kb in moe_bits]
    for mb, cb, kb in moe_variants:
        path = os.path.join(gen, f"moe_inst_mb{mb}_cb{cb}_k{kb}.cu")
        text = (f"#define TRELLIS_INST_MB {mb}\n#define TRELLIS_INST_CB {cb}\n#define TRELLIS_INST_BITS {kb}\n"
                f"#include \"exl3_marlin_moe_inst.h\"\n")
        if not os.path.exists(path) or open(path).read() != text:
            open(path, "w").write(text)
        moe_sources.append(os.path.relpath(path, here))
    moe_fam = os.path.join(gen, "trellis_moe_families.h")
    moe_fam_text = ("// generated by setup.py\n#pragma once\n#define TRELLIS_MOE_VARIANTS(X) "
                    + " ".join(f"X({mb}, {cb}, {kb})" for mb, cb, kb in moe_variants) + "\n")
    if not os.path.exists(moe_fam) or open(moe_fam).read() != moe_fam_text:
        open(moe_fam, "w").write(moe_fam_text)
    moe_ext = cpp_extension.CUDAExtension(
        "trellis_exl3_moe_kernels",
        moe_sources,
        include_dirs=[here, os.path.join(here, "third_party", "marlin"), gen],
        extra_compile_args={"cxx": ["-O3"], "nvcc": nvcc},
    )
    ext_modules = [moe_ext] if moe_mode == "only" else ext_modules + [moe_ext]
# ---- MoE front (end)

setup(
    name="trellis_exl3_kernels",
    version="0.1.0",
    ext_modules=ext_modules,
    cmdclass={"build_ext": cpp_extension.BuildExtension},
)
